# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xho95's Swift Life
email: xho1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Apple에서 공개한 새로운 언어인 Swift를 공부하고 정리하는 사이트입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xho95.github.io" # the base hostname & protocol for your site
twitter_username: xho95
github_username:  xho95

# Build settings
markdown: kramdown
highlighter: rouge
# redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_header", "fenced_code_blocks", "footnotes"]

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: xho95githubio
